language: node_js
node_js:
  - "10.11.0"
cache:
  directories:
    - "node_modules"
addons:
  ssh_known_hosts:
    - tga.ecti.ac.nz
after_success:
  - npm run build
  - cd build
  - git branch
  - git checkout master
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 ../.travis/deploy # this key should have push access
  - ssh-add ../.travis/deploy
  - git remote add deploy administrator@tga.ecti.ac.nz:/home/docker/WEBCONTENT/beta/repo
  - git push deploy
