language: node_js
node_js:
  - "10.11.0"
cache:
  directories:
    - "node_modules"
addons:
  ssh_known_hosts:
    - tga.ecti.ac.nz
before_script:
  - npm run build
  - cp setup.sh build/setup.sh
  - cd build
script:
  - ./setup.sh