version: "3"
  
services:
  cicd:
    image: node:10.11.0
    ports:
        - "3000:3000"
        - "5000:5000"
    volumes:
      - /home/administrator/trials3/app:/app
    working_dir: /app
    command: npm run build